CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO tasks (id, title, done)
SELECT v.id, v.title, v.done
FROM (VALUES
    (1, 'Read the assignment', TRUE),
    (2, 'Build the CRUD API', FALSE),
    (3, 'Push to GitHub', FALSE)
) AS v(id, title, done)
WHERE NOT EXISTS (SELECT 1 FROM tasks);

SELECT setval(
    pg_get_serial_sequence('tasks', 'id'),
    COALESCE((SELECT MAX(id) FROM tasks), 1)
);
